on: [push]
jobs:
  print_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: clean install
        run: mvn clean install
      - name: cobertura
        run: mvn cobertura:cobertura -Dcobertura.report.format=xml