on: [push]
jobs:
  print_hello:
    runs-on: mavenubuntu
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: clean install
        run: mvn clean install
      - name: cobertura
        run: mvn cobertura:cobertura -Dcobertura.report.format=xml
      - name: Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}